-- # Decoration Settings
--
-- # Hyprland Wiki Links
-- # Animation - https://wiki.hypr.land/Configuring/Animations/
-- # Decoration - https://wiki.hypr.land/Configuring/Variables/#decoration
--
-- # Sourcing colors generated by wallust
-- require("wallust/wallust-hyprland")
--
-- hl.config({
--   general = {
--     border_size = 2,
--     gaps_in = 2,
--     gaps_out = 4,
--
--     col = {
--       active_border = "rgb(00d0ff)",
--       inactive_border = "rgb(00748f)",
--     },
--   },
--
--   decoration = {
--     rounding = 0,
--
--     active_opacity = 1.0,
--     inactive_opacity = 0.9,
--     fullscreen_opacity = 1.0,
--
--     dim_inactive = true,
--     dim_strength = 0.1,
--     dim_special = 0.8,
--
--     shadow = {
--       enabled = true,
--       range = 3,
--       render_power = 1,
--       color = "$color12",
--       color_inactive = "$color10",
--     },
--
--     blur = {
--       enabled = true,
--       size = 12,
--       passes = 3,
--       ignore_opacity = true,
--       new_optimizations = true,
--       special = true,
--       popups = true,
--     },
--   },
--
--   group = {
--     col = {
--       border_active = "$color15",
--     },
--     groupbar = {
--       col = {
--         active = "$color0",
--       },
--     },
--   },
-- })

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 10,

		border_size = 2,

		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		col = {
			-- active_border = "rgba(616161ff)",
			-- active_border = "rgba(75F1FAff)",
			active_border = {
				colors = {
					"rgba(ff0000ff)",
					"rgba(ff7f00ff)",
					"rgba(ffff00ff)",
					"rgba(00ff00ff)",
					"rgba(0088ffff)",
					"rgba(aa44ffff)",
				},
				angle = 270,
			},
			inactive_border = "rgba(292929ff)",
		},

		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,

		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,

		-- layout = "dwindle"
	},

	decoration = {
		rounding = 10,
		rounding_power = 10,

		active_opacity = 0.9,
		inactive_opacity = 0.875,
		fullscreen_opacity = 1.0,

		blur = {
			enabled = true,
			xray = false,
			special = false,
			new_optimizations = true,
			size = 20,
			passes = 3,
			brightness = 1,
			noise = 0.01,
			contrast = 0.89,
			ignore_opacity = true,
			vibrancy = 0.5,
			vibrancy_darkness = 0.5,
			popups = true,
			popups_ignorealpha = 0.6,
			input_methods = true,
			input_methods_ignorealpha = 0.8,
		},

		shadow = {
			enabled = true,
			-- ignore_window = true
			range = 15,
			-- offset = "0 2"
			render_power = 3,
			color = "rgba(1a1b2699)",
		},

		-- Dim
		dim_inactive = true,
		dim_strength = 0.05,
		dim_special = 0.07,
	},
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-borders-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-borders-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		-- pseudotile = true -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true, -- You probably want this
	},
})
