general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called) 
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch dpms on # turn on screen after sleep (not strictly necessary, but just in case)
}

listener {
   timeout = 200
   on-timeout = brightnessctl -s set 10
   on-resume = brightnessctl -r
}

listener {
   timeout = 400
   on-timeout = hyprctl dispatch dpms off
   on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
   timeout = 450
   on-timeout = loginctl lock-session
}

listener {
   timeout = 550
   on-timeout = systemctl suspend
}

