# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C5EAF3
background         #1A1B23
cursor             #62829A

active_tab_foreground     #1A1B23
active_tab_background     #C5EAF3
inactive_tab_foreground   #C5EAF3
inactive_tab_background   #1A1B23

active_border_color   #C5EAF3
inactive_border_color #1A1B23
bell_border_color     #001331

color0      #40424A
color1		#001331
color2		#001331
color3		#041B38
color4		#19435D
color5		#2D6B81
color6		#4293A6
color7		#A3D9E6
color8		#7298A1
color9		#001A41
color10		#001A41
color11		#06254B
color12		#215A7B
color13		#3D8FAC
color14		#58C4DD
color15		#A3D9E6
