# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DDDBDB
background         #16171A
cursor             #8391A6

active_tab_foreground     #16171A
active_tab_background     #DDDBDB
inactive_tab_foreground   #DDDBDB
inactive_tab_background   #16171A

active_border_color   #DDDBDB
inactive_border_color #16171A
bell_border_color     #1E3555

color0      #3C3E42
color1		#1E3555
color2		#1F3655
color3		#354863
color4		#4F5E71
color5		#767373
color6		#767373
color7		#C6C4C4
color8		#8B8989
color9		#284771
color10		#294872
color11		#466084
color12		#697D97
color13		#9E9999
color14		#9E9999
color15		#C6C4C4
