# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EBEFF5
background         #131517
cursor             #8693A5

active_tab_foreground     #131517
active_tab_background     #EBEFF5
inactive_tab_foreground   #EBEFF5
inactive_tab_background   #131517

active_border_color   #EBEFF5
inactive_border_color #131517
bell_border_color     #071018

color0      #3A3C3F
color1		#071018
color2		#192940
color3		#405C79
color4		#405C79
color5		#405C79
color6		#949EA9
color7		#DAE0E8
color8		#989DA2
color9		#091620
color10		#213656
color11		#567AA1
color12		#567AA1
color13		#567AA1
color14		#C5D2E1
color15		#DAE0E8
