background                #292c33
foreground                #ffffff

selection_background      #4a4f5a
selection_foreground      #ffffff

url_color                 #83a5d6

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #ffffff
cursor_text_color         #292c33

active_border_color       #83a5d6
inactive_border_color     #3a3f48
bell_border_color         #c55757
visual_bell_color         none

active_tab_background     #292c33
active_tab_foreground     #ffffff
inactive_tab_background   #3a3f48
inactive_tab_foreground   #c5c8c6
tab_bar_background        none
tab_bar_margin_color      none

color0                    #1d1f21
color1                    #bf6b69
color2                    #b7bd73
color3                    #e9c880
color4                    #88a1bb
color5                    #ad95b8
color6                    #95bdb7
color7                    #c5c8c6

color8                    #666666
color9                    #c55757
color10                   #bcc95f
color11                   #e1c65e
color12                   #83a5d6
color13                   #bc99d4
color14                   #83beb1
color15                   #eaeaea
