# you can choose themes from $HOME/.config/kitty/kitty-themes/ oringinally: FantasqueSansM Nerd Font Mono Bold
include ./kitty-themes/00-Default.conf
#include current-theme.conf

# font_family JetBrainsMono Nerd Font
font_family Iosevka
font_size 11.5
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.7
background_blur 1
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 10000
wheel_scroll_min_lines 1

enable_audio_bell no
editor nvim

listen_on unix:/tmp/kitty
shell_integration enabled

window_padding_width 4
allow_remote_control yes
enable_open_actions no
# selection_foreground none
# selection_background none
# foreground #dddddd
# background #000000
# cursor #dddddd


# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME

scrollback_pager sh -c "head -n -1 | NVIM_APPNAME=minimal_nvim nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set readonly nolist' +'$' -"
map kitty_mod+s show_scrollback

