# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1B23)
$foreground = rgb(C5EAF3)
$color0 = rgb(40424A)
$color1 = rgb(001331)
$color2 = rgb(001331)
$color3 = rgb(041B38)
$color4 = rgb(19435D)
$color5 = rgb(2D6B81)
$color6 = rgb(4293A6)
$color7 = rgb(A3D9E6)
$color8 = rgb(7298A1)
$color9 = rgb(001A41)
$color10 = rgb(001A41)
$color11 = rgb(06254B)
$color12 = rgb(215A7B)
$color13 = rgb(3D8FAC)
$color14 = rgb(58C4DD)
$color15 = rgb(A3D9E6)
