# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131517)
$foreground = rgb(EBEFF5)
$color0 = rgb(3A3C3F)
$color1 = rgb(071018)
$color2 = rgb(192940)
$color3 = rgb(405C79)
$color4 = rgb(405C79)
$color5 = rgb(405C79)
$color6 = rgb(949EA9)
$color7 = rgb(DAE0E8)
$color8 = rgb(989DA2)
$color9 = rgb(091620)
$color10 = rgb(213656)
$color11 = rgb(567AA1)
$color12 = rgb(567AA1)
$color13 = rgb(567AA1)
$color14 = rgb(C5D2E1)
$color15 = rgb(DAE0E8)
