# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(151515)
$foreground = rgb(F4F4F4)
$color0 = rgb(2A2A2A)
$color1 = rgb(616161)
$color2 = rgb(6F6F6F)
$color3 = rgb(7D7D7D)
$color4 = rgb(8B8B8B)
$color5 = rgb(999999)
$color6 = rgb(A7A7A7)
$color7 = rgb(E7E7E7)
$color8 = rgb(A1A1A1)
$color9 = rgb(828282)
$color10 = rgb(959595)
$color11 = rgb(A7A7A7)
$color12 = rgb(BABABA)
$color13 = rgb(CCCCCC)
$color14 = rgb(DFDFDF)
$color15 = rgb(E7E7E7)
